# Generated by Django 4.2.11 on 2024-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_walletcurrency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="walletcurrency",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
