# Generated by Django 4.2.11 on 2024-03-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("exchange", "0002_alter_buyorder_trade_pair_alter_sellorder_trade_pair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
