# Generated by Django 4.2.11 on 2024-03-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("exchange", "0003_alter_exchange_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "exchange"), ("model", "buyorder")),
                    models.Q(("app_label", "exchange"), ("model", "sellorder")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
