# Generated by Django 4.2.11 on 2024-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies"},
        ),
        migrations.AddField(
            model_name="currency",
            name="price",
            field=models.IntegerField(default=10),
        ),
    ]
