# Generated by Django 4.2.11 on 2024-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_alter_currency_options_currency_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="price",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
