# Generated by Django 4.2.11 on 2024-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_alter_currency_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
