FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
  && apt-get install -y --no-install-recommends gdal-bin libgdal-dev python3-gdal build-essential \
libpq-dev netcat-openbsd gcc \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /backend
WORKDIR /backend

ENV PYTHONDONTWRITERYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /backend

RUN alias python=python3
RUN pip install psycopg2

RUN pip install -r requirements.txt
COPY . /backend
EXPOSE 8000

ENV DJANGO_ENV=development
ENV DB_HOST=postgres_db
ENV DB_NAME=DB_NAME
ENV DB_PASS=DB_PASS
ENV DB_USER=DB_USER




